apiVersion: v1
kind: Namespace
metadata:
  name: rainercloud
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rainercloud-github-deployer
  namespace: rainercloud
---
# Token Secret for the ServiceAccount (for legacy-style token retrieval)
apiVersion: v1
kind: Secret
metadata:
  name: rainercloud-github-deployer-token
  namespace: rainercloud
  annotations:
    kubernetes.io/service-account.name: rainercloud-github-deployer
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rainercloud-github-deployer-role
  namespace: rainercloud
rules:
  # Core API resources
  - apiGroups: [""]
    resources:
      - pods
      - services
      - configmaps
      - secrets
      - events
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Workloads
  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Batch resources
  - apiGroups: ["batch"]
    resources:
      - cronjobs
      - jobs
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Autoscaling (HPA managed by Helm)
  - apiGroups: ["autoscaling"]
    resources:
      - horizontalpodautoscalers
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Networking (for ingress-managed services)
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Gateway API (HTTPRoute, Gateway, etc.)
  - apiGroups: ["gateway.networking.k8s.io"]
    resources:
      - httproutes
      - gateways
      - referencegrants
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rainercloud-github-deployer-binding
  namespace: rainercloud
subjects:
  - kind: ServiceAccount
    name: rainercloud-github-deployer
    namespace: rainercloud
roleRef:
  kind: Role
  name: rainercloud-github-deployer-role
  apiGroup: rbac.authorization.k8s.io
